### ISSUE TITLE
No data received by watch

### ISSUE THREAD

**Issue by corneliusroemer** [trupici/G-Watch-Wear#1]
I've just set up my galaxy watch 4 and installed the wear OS app.

Unfortunately, while the phone app receives values from the patched Dexcom app, the values don't appear on the watch face.

I use a OnePlus 8 with Android 12.

Any idea what's going on? How can I debug why the watch doesn't receive values. Bit of a bummer :l But the app sounds great so willing to help!

**Comment by trupici** [comment]
Could you please send me a photo of your watch screen and also a screenshot
of mobile gwatch Packet view screen (wait at least 5 minutes there before
you make a screenshot)?

Juraj

Dňa so 4. 6. 2022, 17:30 Cornelius Roemer ***@***.***>
napísal(a):
