### ISSUE TITLE
Digital watch face goes completely white over time, galaxy s6 classic

### ISSUE THREAD

**Issue by stephend61** [trupici/G-Watch-Wear#15]
Hi,  I just got new S6 watch and installed your wear version, but over time the watch face goes completely white and you can't see the face any more.
![20230918_132125](https://github.com/trupici/G-Watch-Wear/assets/33674421/b08c408d-4448-4875-8713-f750cf2ef640)
See image.
I was using the tizen version and it worked perfectly.
Thanks.

**Comment by stephend61** [comment]
![Uploading 20230918_133105.jpg…]()

**Comment by stephend61** [comment]
![20230918_133105](https://github.com/trupici/G-Watch-Wear/assets/33674421/33a5280a-044f-48a5-8f72-192120d44883)
Here it is completely white

**Comment by trupici** [comment]
Issue is already solved, it will be fixed in the next version. In the meantime you can remove/clear the upper complications or use another watch face
