### ISSUE TITLE
Wear display does not work if watch is restarted?

### ISSUE THREAD

**Issue by nigzak** [trupici/G-Watch-Wear#16]
I have observed that there is an issue with restarting the watch (I shutdown the watch over night, got too hot while loading to me :D)
Watch: Galaxy Watch 4 using G-Watch Wear Watchface (digital)

After restarting the watch the watch a VERY long time did not show any data ("no data" alert also triggered)
I did the following things:
- disabled WLAN on watch (don't know if this has any impact ... per default this was ON)
=> this did not solve the issue I think

- open the watch app on phone (S9), change one of the configurations (system language set to english) to trigger a new configuration
=> after this the watch immediately worked again.

Could it be that there is a "connect" issue if you shutdown the watch and start it later? Seems to me that this is not a very good case and probably there should be added a button to trigger it manual ("sync now with watch") or else?

My observations also could be totally random ... I only use this app now for 1 day and it is VERY VERY nice, this is the only thing I have seen what makes it slightly bad. Also the "no data" alert is triggered already when the watch started, if this is a known behaviour it could be a good case to add a delay on it (no "no data" alert after starting watch for xyz minutes)?

In addition if you restart the watch it could be a good thing (if possible) to send chart data which is longer there on the phone but not (yet) on the watch to have also historic informations (don't know if possible)

**Comment by trupici** [comment]
Youbcan reconnect the watch using Reconnect (!) button in the Packet view
screen, see wiki for details.

The mobile app has no database with stored values, the widget graph
internal data can't be used to fill the history on the watch.

The solution is to keep data in persistent db on the watch. The solution
used on Tizen watch to keep data was ported to gwatch wear app but the
result is as you describe.
I have a prototype with db already but it is not finished yet and the
current development is stalled, sorry.

Dňa po 18. 9. 2023, 10:22 nigzak ***@***.***> napísal(a):

**Comment by nigzak** [comment]
Thanks for the update, closing this than for now
