### ISSUE TITLE
diagonal arrows are "replaced" with system icon (blue background) on watch and android app

### ISSUE THREAD

**Issue by nigzak** [trupici/G-Watch-Wear#17]
The diagonal ("angle") arrow is replaced on android (S9) and wear (watch 4) with an icon with blue background.
It seems that android detects using an system icon instead of an "plain" icon?

It would be nice if this could be fixed to be a standard arrow and not an "icon" (or with blue background).
Hint: 
not affected:
- straight arrow ("arrow to right")
- arrow up
- arrow down

affected:
- diagonal arrow up
- diagonal arrow down

Example picture:
![image](https://github.com/trupici/G-Watch-Wear/assets/102737855/4a05b7ca-fbc4-499f-b756-5d998c29a655)

**Comment by trupici** [comment]
The arrow is a character and in the default watch font it has the blue
rectangle around. Change the default font to another and it will disappear.
This is described in wiki, so no need to open an issue. I won't do anything
with it.

Dňa po 18. 9. 2023, 19:22 nigzak ***@***.***> napísal(a):
