### ISSUE TITLE
No connection to librelinkup server since Alibre server maintenance

### ISSUE THREAD

**Issue by User47110815** [trupici/G-Watch-Wear#18]
Hello all,

Issue exists since server maintenance from Alibre. Hope there is a Quick fix possible?

Cheers 

#
![Screenshot_20231005_152533_G-Watch Wear App](https://github.com/trupici/G-Watch-Wear/assets/147068185/f4774f71-7986-4cc6-b491-cc228b432071)

**Comment by trupici** [comment]
This is not a problem of gwatch. Open LibreLinkUp app on your mobile, log
off, log on again, accept new policies and it will work again.
Follow the discussions in G-Watch App Users group

Dňa št 5. 10. 2023, 15:29 User47110815 ***@***.***>
napísal(a):

**Comment by Igor-bubble** [comment]
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
@font-face
	{font-family:"Blackadder ITC";
	panose-1:4 2 5 5 5 16 7 2 13 2;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0cm;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:612.0pt 792.0pt;
	margin:72.0pt 72.0pt 72.0pt 72.0pt;}
div.WordSection1
	{page:WordSection1;}

**Comment by User47110815** [comment]
Thank you for the fast feedback,  it worked! I would never have relogged into linkup because it showed the actual values. Thanks for your help! Have a good night
