### ISSUE TITLE
Android 14 Pixel 7 Problems

### ISSUE THREAD

**Issue by ChrisJSLH** [trupici/G-Watch-Wear#19]
With data source set as juggluco the widgets aren't updating reliably. The delta isn't changing at all and the graph isn't drawing.

**Comment by suside** [comment]
Check if this helps https://github.com/trupici/G-Watch-Wear/issues/21#issuecomment-1773694191

**Comment by ChrisJSLH** [comment]
> Check if this helps [#21 (comment)](https://github.com/trupici/G-Watch-Wear/issues/21#issuecomment-1773694191)

No, I'm not using AAPS. I'm using it with Juggluco.

**Comment by trupici** [comment]
The current version of the app was adopted to Android 13, in that time there was no Android 14 available. The next version will handle this issue

**Comment by trupici** [comment]
fix: 4746b494ed8d5f31de9bf76107d39fec21e6fbcd

Still waiting for Android14 upgrade on my S23+ to make final tests on real HW

**Comment by Rescueme14** [comment]
> arreglar: [4746b49](https://github.com/trupici/G-Watch-Wear/commit/4746b494ed8d5f31de9bf76107d39fec21e6fbcd)
> 
> Sigo esperando la actualización de Android14 en mi S23+ para realizar pruebas finales en HW real

Mi pareja le acaba de llegar en sansung s23 españa.

A ver si puedes probar y liberar o incluso liberar version alpha por aquí

**Comment by trupici** [comment]
Thanks, already got the update too. In the next days I'll make the new release

**Comment by trupici** [comment]
fixed in version 0.9.7
