### ISSUE TITLE
Dexcom share work only for 24h

### ISSUE THREAD

**Issue by Joga1-2000** [trupici/G-Watch-Wear#2]
I use Dexcom Share as Datasource with a G7 Sensor.
It works absolutely fine for arround 24h then a got error:

Sending Dexcom Share auth request...
FAILED: AccountPasswordInvalid

Than i have to deactivat and reactivate the Datasource and send the settings. After that everything works again for 24h.
![Screenshot_20230205_124018_G-Watch Wear App](https://user-images.githubusercontent.com/124501723/216817350-133697e4-ecb5-4cae-824d-793e36c29e55.jpg)

Use Version 0.9.5

**Comment by trupici** [comment]
Thank you for reporting it.

Juraj

Dňa ne 5. 2. 2023, 12:58 Joga1-2000 ***@***.***> napísal(a):

**Comment by trupici** [comment]
Please, could you try it with the version 0.9.7? The follower logic was rewritten due to other changes

**Comment by Joga1-2000** [comment]
The issue fixed itself some Monthe ago. 
But with your new Version 0.9.7 everything still works fine.
Thank you for your work.
