### ISSUE TITLE
Vibration alarms

### ISSUE THREAD

**Issue by Waxwax462** [trupici/G-Watch-Wear#20]
Please make silent vibration alarms during daytome possible. Nobody needs funky-alarm sounds while he is not sleeping. Customizable time periods would be awsome like silent/vibration alarms in daytime und funky alarm sounds in the night. Thank you very much for your work

Kind regards

**Comment by trupici** [comment]
The G-Watch Wear App is still in beta stage, once there will be a version 1.x then the alarm options will be updated as it was in classic gwatch app, including active time range
