### ISSUE TITLE
On wearOS4 3rd party complication shows actual value too small vs delta value

### ISSUE THREAD

**Issue by JawsAT** [trupici/G-Watch-Wear#23]
First, thanks for this app, it works great!
On my new Pixel Watch 2 however the 3rd party complication shows the delta value much larger than the actual value, this makes the actual value really hard to read (I'm not getting younger).
See attached screenshot. 
![screenshot-2023-10-22-20-33-31](https://github.com/trupici/G-Watch-Wear/assets/148716376/bfba82e3-a7c1-49e4-8e0f-1c85af7b331a)

My assumption is that this is due to WearOS4 (rather than Pixel Watch 2).
So I would kindly ask you to either "fix" this by swapping these values and make the actual value larger with the delta below and smaller - or make this an option.
Your support is greatly appreciated, thank you!

**Comment by Saortica** [comment]
Can confirm I have this issue as well, on pw2. Same readability problem with 'not getting younger' vision lol.

**Comment by trupici** [comment]
This is not so straightforward. The complication has only one mandatory field (text) and then optional filed title and icon. I put the BG value in text field, and delta in the title field on purpose: the watch face is responsible for rendering of complication data, and some faces do not render title at all - so you would end with delta only or icon + delta. Therefore, the bg value is filled into mandatory text field to be always displayed.
I hope you understand what I want to say.
I will look at it what can be done, but I don't want just to swap them. I had it at the very beginning and it was really not good on some faces...

**Comment by igor-xdrip** [comment]
One possible solution would be to add an extra complication with Title and Text contents swapped. "Misbehaving" watch faces can use existing complication, "well behaved" would give the user an opportunity to use a modified one.

**Comment by rspier** [comment]
It sounds like there's some watch/watch-face specific stuff here that's hard to predict.

Would a runtime configuration option be a solution?  (Similar to a different complication, but more extensible.)

* Text/Title
* Title/Text

This would also open the door for variations like "only show trend, don't show delta"

**Comment by JawsAT** [comment]
Fixed with 0.9.8 - thank you!
