### ISSUE TITLE
G-Watch App Wear can't be found in app store.

### ISSUE THREAD

**Issue by ms0uto** [trupici/G-Watch-Wear#26]
As title says app can't be found from app store anymore (on the watch)
It does show on the phone but it won't on the wear os watch.

I am using a Samsung Galaxy Watch 6.
Tried every way, even using some sideloader to install the apk.
Watch won't show the app ever so I can't set the watch face to the g watch one.

Is there a way to get the glucose mask showing on the Galaxy 6 watch?

THANKS

**Comment by MarcinLachowicz** [comment]
Original comment from admin:
```
Today I've received email from Google that the Gwatch Wear watch face app has been temporary removed from the store due to missing scrollbar in the watch face configuration screen (it breaks google ui requirements).
So, it won't be available for a while until I publish an update addressing this issue. Update requires to migrate to the latest WearOS SDK and other libs, otherwise it won't be accepted.
Please, be patient
```

**Comment by ms0uto** [comment]
@MarcinLachowicz  Thanks for the information!!
