### ISSUE TITLE
Unable to change to mmol

### ISSUE THREAD

**Issue by disturbedgd** [trupici/G-Watch-Wear#5]
Hi, I have a Samsung Smart Watch 5 and I'm using xdrip. I changed the setting on G-Watch app to show the units as mmol but on my watch it remains mg/dl. Xdrip is also configured to show it as mmol. How can I fix this?

**Comment by waseltzer** [comment]
I have this problem, too.
I was able to fix it by switching the the G-Watch watch face, Customize, change units.
Sometimes, this doesn't work until I restart the watch.

**Comment by disturbedgd** [comment]
Thanks, If you customize it on the watch with the default G-Watch face and swipe right you will go past the alarm settings and find one that says use mmol. But as far as customizing other watch faces go I don't know.

**Comment by trupici** [comment]
This config is shared between the both gwatch watch faces and also with
gwatch complication provider. so, once you set it for the gwatch watch face
it will also change for gwatch complication if used in other watch faces -
you just need to wait for the next bg reading to see the change.

Juraj
