### ISSUE TITLE
LibreLinkUp broken after LLU update

### ISSUE THREAD

**Issue by eichmat** [trupici/G-Watch-Wear#7]
Abbott updated LLU on 14/JUN/2023 which has broken the G-Watch Wear integration.  After updating to LLU 4.7.0, now get HTTP 403 errors in the logs...

**Comment by tagunter** [comment]
It appears that Abbott broke something on the back end. That's why LLU doesn't show a current reading either, only the graph and associated average readings. See my [issue #6](https://github.com/trupici/G-Watch-Wear/issues/6) for some more info I got from another source. Also, I was getting OK earlier (just no updated data) after updating to 4.7, before it changed to 403.

**Comment by ojalaj** [comment]
So you are also not getting any data to G-Watch Wear at the moment? Only 403's?

**Comment by tagunter** [comment]
> So you are also not getting any data to G-Watch Wear at the moment? Only 403's?

Correct, I am getting OK on auth but "FAILED: HTTP 403 -" on session request

**Comment by eichmat** [comment]
Same here...  Looks like they fixed the LLU app overnight as it now shows the most recent reading (though the graph has the next data point 20-minutes old, with all data points after that stepping by 5-minute increments--I'm sure this is to reduce the amount of data they have to put in the JSON file).

I saw on Reddit and Facebook that Nightscout/XDrip+ is suffering the same API issue.  Another Reddit post indicated that Abbott blocked pre-4.7 API calls a week earlier than apparently had been expected...  I guess we need to hope that Trupici can push out an update ASAP...  I'm sure the others

**Comment by BoHellgren** [comment]
Is Juray Antal (trupici.sk@gmail.com) still maintaining this app?

**Comment by trupici** [comment]
Yes, I am. I've got hundreds of emails and PMs related to this LLU change.  The fix is ready, hotifx test app is available for download in G-Watch App Users group on fb. You need to side load the watch app on the watch if you want to see your numbers - due to different test app signature.
